apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: kc-docs.kr-central-2.kcr.dev/tutorial/kakaocloud-library-server:32da91bcd3c0b2398566918a1e8859e9a5e3dc2d
          name: kakaocloud-library-server
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: "local"
            - name: SERVER_PORT
              value: "8080"
      imagePullSecrets:
        - name: kc-tutorial-cr
