apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: kc-docs.kr-central-2.kcr.dev/tutorial/kakaocloud-library-client:e67b1fa165a3c1d51ac05e1080750a960a355ee7
          name: kakaocloud-library-client
          ports:
            - containerPort: 80
          env:
            - name: SERVER_ENDPOINT
              value: "http://server.kakaocloud-library.svc.cluster.local:8080"
      imagePullSecrets:
        - name: kc-tutorial-cr
